title: Ravi Teja P V # your name (or website title) here
logo: "/images/coder1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Development Specialist
  Data Migration
  <br><br>
  <a href="https://www.linkedin.com/in/ravitejapv/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
